// Builds public/css/wp.css from the scraped WordPress site: every linked stylesheet and inline
// <style> block, in document order, deduplicated rule by rule. Also copies the theme fonts.
// Usage: node scripts/extract-css.mjs [path-to-scrape]
import fs from 'node:fs';
import path from 'node:path';

const SCRAPE = path.resolve(process.argv[2] ?? '../erwan-rivet.fr');
const OUT_CSS = path.resolve('public/css/wp.css');
const OUT_FONTS = path.resolve('public/fonts');

function htmlFiles(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (!['app', 'wp', 'wp-json', 'pagespeed_static', 'feed'].includes(e.name)) out.push(...htmlFiles(p));
    } else if (e.name === 'index.html' || e.name === 'projets-personnels.html') {
      out.push(p);
    }
  }
  return out;
}

/** Splits a stylesheet into top-level rules (at-rules keep their whole block). */
function splitRules(css) {
  css = css.replace(/\/\*[\s\S]*?\*\//g, '').replace(/@charset[^;]*;/g, '');
  const rules = [];
  let depth = 0;
  let start = 0;
  let quote = null;
  for (let i = 0; i < css.length; i++) {
    const c = css[i];
    if (quote) {
      if (c === '\\') i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'") quote = c;
    else if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) {
        rules.push(css.slice(start, i + 1).trim());
        start = i + 1;
      }
    } else if (c === ';' && depth === 0) {
      rules.push(css.slice(start, i + 1).trim());
      start = i + 1;
    }
  }
  return rules.filter(Boolean);
}

const seen = new Set();
const output = [];
function add(css) {
  for (const rule of splitRules(css)) {
    const key = rule.replace(/\s+/g, ' ');
    if (seen.has(key)) continue;
    seen.add(key);
    output.push(rule);
  }
}

// Home page first so its rules come first, like on the original site.
const home = path.join(SCRAPE, 'index.html');
const files = htmlFiles(SCRAPE).sort((a, b) => (b === home) - (a === home));
for (const file of files) {
  let html = fs.readFileSync(file, 'utf8');
  html = html.slice(0, html.indexOf('<body')).replace(/<noscript[\s\S]*?<\/noscript>/g, '');
  const re = /<link[^>]*rel=["']?stylesheet[^>]*href=["']?([^\s"'>]+)[^>]*>|<style[^>]*>([\s\S]*?)<\/style>/g;
  for (const m of html.matchAll(re)) {
    if (m[1]) {
      const rel = decodeURIComponent(m[1].replace(/%3F/gi, '?')).replace(/^(\.\.\/)+/, '');
      const candidates = [rel, rel.replace('?', '')];
      const found = candidates.map((c) => path.join(SCRAPE, c)).find((p) => fs.existsSync(p));
      if (found) add(fs.readFileSync(found, 'utf8'));
      else console.warn('missing stylesheet', rel);
    } else {
      add(m[2]);
    }
  }
}

let css = output.join('\n');
css = css.replace(/url\(['"]?(?:\.\.\/)*app\/themes\/twentytwentyfive\/assets\/fonts\/[^/]+\/([^'")]+)['"]?\)/g, "url('/fonts/$1')");

fs.mkdirSync(path.dirname(OUT_CSS), { recursive: true });
fs.writeFileSync(OUT_CSS, `/* Generated by scripts/extract-css.mjs from the original WordPress site. */\n${css}\n`);

fs.mkdirSync(OUT_FONTS, { recursive: true });
for (const font of ['fira-code/FiraCode-VariableFont_wght.woff2', 'manrope/Manrope-VariableFont_wght.woff2']) {
  fs.copyFileSync(path.join(SCRAPE, 'app/themes/twentytwentyfive/assets/fonts', font), path.join(OUT_FONTS, path.basename(font)));
}
console.log(`wp.css: ${output.length} rules, ${(css.length / 1024).toFixed(1)} KB from ${files.length} pages`);
